//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FillWS_NET.FillWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fillWS.streetmaster/", ConfigurationName="FillWS.Fill")]
    public interface Fill {
        
        // CODEGEN: Il parametro 'TotOutFill' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://fillWS.streetmaster/Fill/FillRequest", ReplyAction="http://fillWS.streetmaster/Fill/FillResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TotOutFill")]
        FillWS_NET.FillWS.FillResponse Fill(FillWS_NET.FillWS.FillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fillWS.streetmaster/Fill/FillRequest", ReplyAction="http://fillWS.streetmaster/Fill/FillResponse")]
        System.Threading.Tasks.Task<FillWS_NET.FillWS.FillResponse> FillAsync(FillWS_NET.FillWS.FillRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fillWS.streetmaster/")]
    public partial class inputCommon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string capField;
        
        private string civicoField;
        
        private string dugField;
        
        private string indirizzoField;
        
        private string localitaField;
        
        private string localita2Field;
        
        private string provinciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string civico {
            get {
                return this.civicoField;
            }
            set {
                this.civicoField = value;
                this.RaisePropertyChanged("civico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dug {
            get {
                return this.dugField;
            }
            set {
                this.dugField = value;
                this.RaisePropertyChanged("dug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string localita {
            get {
                return this.localitaField;
            }
            set {
                this.localitaField = value;
                this.RaisePropertyChanged("localita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string localita2 {
            get {
                return this.localita2Field;
            }
            set {
                this.localita2Field = value;
                this.RaisePropertyChanged("localita2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fillWS.streetmaster/")]
    public partial class infoShort : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comuneField;
        
        private string dugField;
        
        private string frazioneField;
        
        private string indirizzoField;
        
        private string toponimoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
                this.RaisePropertyChanged("comune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dug {
            get {
                return this.dugField;
            }
            set {
                this.dugField = value;
                this.RaisePropertyChanged("dug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string frazione {
            get {
                return this.frazioneField;
            }
            set {
                this.frazioneField = value;
                this.RaisePropertyChanged("frazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string toponimo {
            get {
                return this.toponimoField;
            }
            set {
                this.toponimoField = value;
                this.RaisePropertyChanged("toponimo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fillWS.streetmaster/")]
    public partial class infoPostale : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comuneField;
        
        private string comuneShortField;
        
        private string dugField;
        
        private string dugComplField;
        
        private string frazioneField;
        
        private string frazioneShortField;
        
        private string isFrazionePTField;
        
        private string isStradaPTField;
        
        private string rigaAggiuntivaField;
        
        private string rigaEdificioField;
        
        private string rigaIndirizzoField;
        
        private string rigaLocalitaField;
        
        private string toponimoField;
        
        private string toponimoShortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
                this.RaisePropertyChanged("comune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string comuneShort {
            get {
                return this.comuneShortField;
            }
            set {
                this.comuneShortField = value;
                this.RaisePropertyChanged("comuneShort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dug {
            get {
                return this.dugField;
            }
            set {
                this.dugField = value;
                this.RaisePropertyChanged("dug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dugCompl {
            get {
                return this.dugComplField;
            }
            set {
                this.dugComplField = value;
                this.RaisePropertyChanged("dugCompl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string frazione {
            get {
                return this.frazioneField;
            }
            set {
                this.frazioneField = value;
                this.RaisePropertyChanged("frazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string frazioneShort {
            get {
                return this.frazioneShortField;
            }
            set {
                this.frazioneShortField = value;
                this.RaisePropertyChanged("frazioneShort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string isFrazionePT {
            get {
                return this.isFrazionePTField;
            }
            set {
                this.isFrazionePTField = value;
                this.RaisePropertyChanged("isFrazionePT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string isStradaPT {
            get {
                return this.isStradaPTField;
            }
            set {
                this.isStradaPTField = value;
                this.RaisePropertyChanged("isStradaPT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string rigaAggiuntiva {
            get {
                return this.rigaAggiuntivaField;
            }
            set {
                this.rigaAggiuntivaField = value;
                this.RaisePropertyChanged("rigaAggiuntiva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string rigaEdificio {
            get {
                return this.rigaEdificioField;
            }
            set {
                this.rigaEdificioField = value;
                this.RaisePropertyChanged("rigaEdificio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string rigaIndirizzo {
            get {
                return this.rigaIndirizzoField;
            }
            set {
                this.rigaIndirizzoField = value;
                this.RaisePropertyChanged("rigaIndirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string rigaLocalita {
            get {
                return this.rigaLocalitaField;
            }
            set {
                this.rigaLocalitaField = value;
                this.RaisePropertyChanged("rigaLocalita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string toponimo {
            get {
                return this.toponimoField;
            }
            set {
                this.toponimoField = value;
                this.RaisePropertyChanged("toponimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string toponimoShort {
            get {
                return this.toponimoShortField;
            }
            set {
                this.toponimoShortField = value;
                this.RaisePropertyChanged("toponimoShort");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fillWS.streetmaster/")]
    public partial class infoGeo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string omiField;
        
        private string sez1991Field;
        
        private string sez2001Field;
        
        private string sez2011Field;
        
        private string sideField;
        
        private int warningField;
        
        private double xField;
        
        private double x1Field;
        
        private double yField;
        
        private double y1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string omi {
            get {
                return this.omiField;
            }
            set {
                this.omiField = value;
                this.RaisePropertyChanged("omi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sez1991 {
            get {
                return this.sez1991Field;
            }
            set {
                this.sez1991Field = value;
                this.RaisePropertyChanged("sez1991");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sez2001 {
            get {
                return this.sez2001Field;
            }
            set {
                this.sez2001Field = value;
                this.RaisePropertyChanged("sez2001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sez2011 {
            get {
                return this.sez2011Field;
            }
            set {
                this.sez2011Field = value;
                this.RaisePropertyChanged("sez2011");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
                this.RaisePropertyChanged("side");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
                this.RaisePropertyChanged("warning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double x1 {
            get {
                return this.x1Field;
            }
            set {
                this.x1Field = value;
                this.RaisePropertyChanged("x1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double y1 {
            get {
                return this.y1Field;
            }
            set {
                this.y1Field = value;
                this.RaisePropertyChanged("y1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fillWS.streetmaster/")]
    public partial class infoDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string belfioreField;
        
        private string cABField;
        
        private string catastoField;
        
        private string civicoField;
        
        private int codComuneField;
        
        private int codStradaField;
        
        private string comuneMultiCapField;
        
        private string dugField;
        
        private string istatComuneField;
        
        private string istatProvField;
        
        private string istatRegioneField;
        
        private string provEstesaField;
        
        private string regioneField;
        
        private string stradaMultiCapField;
        
        private string toponimoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string belfiore {
            get {
                return this.belfioreField;
            }
            set {
                this.belfioreField = value;
                this.RaisePropertyChanged("belfiore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CAB {
            get {
                return this.cABField;
            }
            set {
                this.cABField = value;
                this.RaisePropertyChanged("CAB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string catasto {
            get {
                return this.catastoField;
            }
            set {
                this.catastoField = value;
                this.RaisePropertyChanged("catasto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string civico {
            get {
                return this.civicoField;
            }
            set {
                this.civicoField = value;
                this.RaisePropertyChanged("civico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codComune {
            get {
                return this.codComuneField;
            }
            set {
                this.codComuneField = value;
                this.RaisePropertyChanged("codComune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int codStrada {
            get {
                return this.codStradaField;
            }
            set {
                this.codStradaField = value;
                this.RaisePropertyChanged("codStrada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string comuneMultiCap {
            get {
                return this.comuneMultiCapField;
            }
            set {
                this.comuneMultiCapField = value;
                this.RaisePropertyChanged("comuneMultiCap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string dug {
            get {
                return this.dugField;
            }
            set {
                this.dugField = value;
                this.RaisePropertyChanged("dug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string istatComune {
            get {
                return this.istatComuneField;
            }
            set {
                this.istatComuneField = value;
                this.RaisePropertyChanged("istatComune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string istatProv {
            get {
                return this.istatProvField;
            }
            set {
                this.istatProvField = value;
                this.RaisePropertyChanged("istatProv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string istatRegione {
            get {
                return this.istatRegioneField;
            }
            set {
                this.istatRegioneField = value;
                this.RaisePropertyChanged("istatRegione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string provEstesa {
            get {
                return this.provEstesaField;
            }
            set {
                this.provEstesaField = value;
                this.RaisePropertyChanged("provEstesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string regione {
            get {
                return this.regioneField;
            }
            set {
                this.regioneField = value;
                this.RaisePropertyChanged("regione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string stradaMultiCap {
            get {
                return this.stradaMultiCapField;
            }
            set {
                this.stradaMultiCapField = value;
                this.RaisePropertyChanged("stradaMultiCap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string toponimo {
            get {
                return this.toponimoField;
            }
            set {
                this.toponimoField = value;
                this.RaisePropertyChanged("toponimo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fillWS.streetmaster/")]
    public partial class infoCivico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string casellaPostaleField;
        
        private string civAddField;
        
        private string civShortField;
        
        private string coloreField;
        
        private string esponenteField;
        
        private double kmField;
        
        private int numCivicoField;
        
        private string pressoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string casellaPostale {
            get {
                return this.casellaPostaleField;
            }
            set {
                this.casellaPostaleField = value;
                this.RaisePropertyChanged("casellaPostale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string civAdd {
            get {
                return this.civAddField;
            }
            set {
                this.civAddField = value;
                this.RaisePropertyChanged("civAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string civShort {
            get {
                return this.civShortField;
            }
            set {
                this.civShortField = value;
                this.RaisePropertyChanged("civShort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string colore {
            get {
                return this.coloreField;
            }
            set {
                this.coloreField = value;
                this.RaisePropertyChanged("colore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string esponente {
            get {
                return this.esponenteField;
            }
            set {
                this.esponenteField = value;
                this.RaisePropertyChanged("esponente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double km {
            get {
                return this.kmField;
            }
            set {
                this.kmField = value;
                this.RaisePropertyChanged("km");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int numCivico {
            get {
                return this.numCivicoField;
            }
            set {
                this.numCivicoField = value;
                this.RaisePropertyChanged("numCivico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string presso {
            get {
                return this.pressoField;
            }
            set {
                this.pressoField = value;
                this.RaisePropertyChanged("presso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fillWS.streetmaster/")]
    public partial class infoAlter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int capField;
        
        private int comuneField;
        
        private int dugField;
        
        private int frazioneField;
        
        private int provinciaField;
        
        private int viaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
                this.RaisePropertyChanged("comune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dug {
            get {
                return this.dugField;
            }
            set {
                this.dugField = value;
                this.RaisePropertyChanged("dug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int frazione {
            get {
                return this.frazioneField;
            }
            set {
                this.frazioneField = value;
                this.RaisePropertyChanged("frazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
                this.RaisePropertyChanged("via");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fillWS.streetmaster/")]
    public partial class outFill : object, System.ComponentModel.INotifyPropertyChanged {
        
        private infoAlter alterField;
        
        private string capField;
        
        private infoCivico civicoField;
        
        private string comuneField;
        
        private infoDetail detailField;
        
        private string frazioneField;
        
        private infoGeo geoField;
        
        private string indirizzoField;
        
        private infoPostale postaleField;
        
        private string provinciaField;
        
        private int scoreComuneField;
        
        private int scoreStradaField;
        
        private infoShort shortFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public infoAlter alter {
            get {
                return this.alterField;
            }
            set {
                this.alterField = value;
                this.RaisePropertyChanged("alter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public infoCivico civico {
            get {
                return this.civicoField;
            }
            set {
                this.civicoField = value;
                this.RaisePropertyChanged("civico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
                this.RaisePropertyChanged("comune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public infoDetail detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string frazione {
            get {
                return this.frazioneField;
            }
            set {
                this.frazioneField = value;
                this.RaisePropertyChanged("frazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public infoGeo geo {
            get {
                return this.geoField;
            }
            set {
                this.geoField = value;
                this.RaisePropertyChanged("geo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public infoPostale postale {
            get {
                return this.postaleField;
            }
            set {
                this.postaleField = value;
                this.RaisePropertyChanged("postale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int scoreComune {
            get {
                return this.scoreComuneField;
            }
            set {
                this.scoreComuneField = value;
                this.RaisePropertyChanged("scoreComune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int scoreStrada {
            get {
                return this.scoreStradaField;
            }
            set {
                this.scoreStradaField = value;
                this.RaisePropertyChanged("scoreStrada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public infoShort shortFormat {
            get {
                return this.shortFormatField;
            }
            set {
                this.shortFormatField = value;
                this.RaisePropertyChanged("shortFormat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fillWS.streetmaster/")]
    public partial class totOutFill : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codErrField;
        
        private int normField;
        
        private int numCandField;
        
        private outFill[] outItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codErr {
            get {
                return this.codErrField;
            }
            set {
                this.codErrField = value;
                this.RaisePropertyChanged("codErr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int norm {
            get {
                return this.normField;
            }
            set {
                this.normField = value;
                this.RaisePropertyChanged("norm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numCand {
            get {
                return this.numCandField;
            }
            set {
                this.numCandField = value;
                this.RaisePropertyChanged("numCand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public outFill[] outItem {
            get {
                return this.outItemField;
            }
            set {
                this.outItemField = value;
                this.RaisePropertyChanged("outItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fill", WrapperNamespace="http://fillWS.streetmaster/", IsWrapped=true)]
    public partial class FillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fillWS.streetmaster/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FillWS_NET.FillWS.inputCommon inFill;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fillWS.streetmaster/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        public FillRequest() {
        }
        
        public FillRequest(FillWS_NET.FillWS.inputCommon inFill, string key) {
            this.inFill = inFill;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FillResponse", WrapperNamespace="http://fillWS.streetmaster/", IsWrapped=true)]
    public partial class FillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fillWS.streetmaster/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FillWS_NET.FillWS.totOutFill TotOutFill;
        
        public FillResponse() {
        }
        
        public FillResponse(FillWS_NET.FillWS.totOutFill TotOutFill) {
            this.TotOutFill = TotOutFill;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FillChannel : FillWS_NET.FillWS.Fill, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FillClient : System.ServiceModel.ClientBase<FillWS_NET.FillWS.Fill>, FillWS_NET.FillWS.Fill {
        
        public FillClient() {
        }
        
        public FillClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FillClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FillClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FillClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FillWS_NET.FillWS.FillResponse FillWS_NET.FillWS.Fill.Fill(FillWS_NET.FillWS.FillRequest request) {
            return base.Channel.Fill(request);
        }
        
        public FillWS_NET.FillWS.totOutFill Fill(FillWS_NET.FillWS.inputCommon inFill, string key) {
            FillWS_NET.FillWS.FillRequest inValue = new FillWS_NET.FillWS.FillRequest();
            inValue.inFill = inFill;
            inValue.key = key;
            FillWS_NET.FillWS.FillResponse retVal = ((FillWS_NET.FillWS.Fill)(this)).Fill(inValue);
            return retVal.TotOutFill;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FillWS_NET.FillWS.FillResponse> FillWS_NET.FillWS.Fill.FillAsync(FillWS_NET.FillWS.FillRequest request) {
            return base.Channel.FillAsync(request);
        }
        
        public System.Threading.Tasks.Task<FillWS_NET.FillWS.FillResponse> FillAsync(FillWS_NET.FillWS.inputCommon inFill, string key) {
            FillWS_NET.FillWS.FillRequest inValue = new FillWS_NET.FillWS.FillRequest();
            inValue.inFill = inFill;
            inValue.key = key;
            return ((FillWS_NET.FillWS.Fill)(this)).FillAsync(inValue);
        }
    }
}
